name: SMN Scraper Direct Test

on:
  workflow_dispatch: # Solo se ejecutará manualmente

jobs:
  scrape-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: '138'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install selenium requests undetected-chromedriver
      
      - name: Run scraper
        run: python scraper.py
        
      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización de datos del tiempo"
          file_pattern: '*.csv'
