name: SMN Weather Scraper

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # --- INICIO DE LA CORRECCIÓN ---
      # Instalamos selenium Y la librería especializada
      - name: Install dependencies
        run: |
          pip install selenium requests undetected-chromedriver
      # --- FIN DE LA CORRECCIÓN ---

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actualización automática de datos del tiempo"
          file_pattern: '*.json'
